"""Deterministic exact mathematics, the route Facet takes before reasoning."""

from facet_runtime.exact.answer import extract_final_math
from facet_runtime.exact.intercepts import (
    AxisIntercepts,
    Coordinate,
    solve_axis_intercepts,
)
from facet_runtime.exact.linear import solve_linear_function, subject
from facet_runtime.exact.regression import (
    NotThisQuestion,
    fit_quadratic,
    rate_unit,
    regression_optimum,
)
from facet_runtime.exact.result import ExactCallResult, ExactDebugInfo
from facet_runtime.exact.router import (
    ANSWER_FORMS,
    AXIS_INTERCEPTS,
    CHOICE,
    EXACT_METHOD,
    NO_OPERATION_MATCHED,
    ORDERED_PAIR,
    PARTS,
    REGRESSION_METHOD,
    RELATION,
    SCALAR,
    EntryMode,
    ExactlyRefused,
    ExactSolution,
    Relation,
    classify_polynomial,
    entry_text,
    evaluate_real_radical,
    is_prose,
    solve_exact,
    solve_one_equation,
    solve_over_points,
    solve_points_on_quadratic,
    solve_stated_linear_function,
    solve_table_completion,
    solve_vertex,
)
from facet_runtime.exact.table import (
    TABLE_METHOD,
    AnswerTable,
    Representation,
    TableRefused,
    TableUnverifiable,
    complete_table,
    parse_answer_table,
    parse_representation,
    verify_completion,
)

__all__ = [
    "ANSWER_FORMS",
    "AXIS_INTERCEPTS",
    "CHOICE",
    "EXACT_METHOD",
    "NO_OPERATION_MATCHED",
    "ORDERED_PAIR",
    "PARTS",
    "REGRESSION_METHOD",
    "RELATION",
    "SCALAR",
    "TABLE_METHOD",
    "AnswerTable",
    "AxisIntercepts",
    "Coordinate",
    "EntryMode",
    "ExactCallResult",
    "ExactDebugInfo",
    "ExactSolution",
    "ExactlyRefused",
    "NotThisQuestion",
    "Relation",
    "Representation",
    "TableRefused",
    "TableUnverifiable",
    "classify_polynomial",
    "complete_table",
    "entry_text",
    "evaluate_real_radical",
    "extract_final_math",
    "fit_quadratic",
    "is_prose",
    "parse_answer_table",
    "parse_representation",
    "rate_unit",
    "regression_optimum",
    "solve_axis_intercepts",
    "solve_exact",
    "solve_linear_function",
    "solve_one_equation",
    "solve_over_points",
    "solve_points_on_quadratic",
    "solve_stated_linear_function",
    "solve_table_completion",
    "solve_vertex",
    "subject",
    "verify_completion",
]
